export const StaticData = {
    Meta_title:" Maxol Service Station - Find Fuel near you!",
    Meta_description:"Visit Maxol Service Station | ‘Fuels You Can Trust’ is our guarantee to you. All our fuels are quality assured, and our fuel supply can be directly traced to the refinery from which it originated.",
    locator_breadcrumb:"Station Locator",
    FindLocationtext:"Find a Location",
    Usemylocation:"Use my location",
    Search:"Search",
    Brandname:"The Maxol Group",
    miles:"miles",
    tempClosed:"Temporarily Closed",
    StoreDetailbtn:"View Station Detail",
    Storehighlight:"Station Highlights",
    Days:"Days",
    Hours:"Hours",
    Minutes:"Minutes",
    Seconds:"Seconds",
    FAQheading:"How can we help ?",
    getDirection:"Directions",
    AllRegion:"All Regions of",
    NearStoretext:"NEARBY LOCATIONS",
    AllLocationtext:"View All Location",
    PagenotFound:"404 - Page Not Found",
    cantfind_page:"We're really sorry, we can't find the page you're looking for",
    Youcouldtry:"You could try",
    Previuspage:"Going back to the previous page",
    homePage:"Going back to the homepage",
    StoreFinder:"Station Finder",
    FAQs:"FAQs",
    DownloadApp:"Download Our App",
    cookie:"cookies policy",
    Closed:"Closed",
    DayofWeek:"Day of the Week",
    Reopenmessage:"Message - The Station is temporarily closed. It will reopen at",
    Address:"Address",
    Telephone:"Telephone",
    Holdiay:"Holdiday Hours",
    }